# HTTP -> HTTPS

server {
    listen 80;
    server_name api.fch-catechesis.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.fch-catechesis.org;

    access_log /var/log/nginx/api-access.log;
    error_log /var/log/nginx/api-error.log warn;

    location /health {
        allow 127.0.0.1;
        deny all;

        proxy_pass http://api_service;
        include /etc/nginx/conf.d/proxy.conf;

        access_log off;
    }

    location /webhook/ {
        proxy_pass http://api_service;
        include /etc/nginx/conf.d/proxy.conf;
    }
    
    location / {
        limit_req zone=api_limit burst=20 nodelay;
        proxy_pass http://api_service;
        include /etc/nginx/conf.d/proxy.conf;
    }
}