server {
    listen 80;

    server_name fch-catechesis.org;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;

    server_name fch-catechesis.org;

    ssl_certificate /etc/letsencrypt/live/fch-catechesis.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fch-catechesis.org/privkey.pem;

    location / {
        proxy_pass http://web:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Portal
server {
    listen 443 ssl;
    http2 on;

    server_name portal.fch-catechesis.org;

    ssl_certificate /etc/letsencrypt/live/fch-catechesis.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fch-catechesis.org/privkey.pem;

    location / {
        proxy_pass http://portal:3001;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# API
server {
    listen 443 ssl;
    http2 on;

    server_name api.fch-catechesis.org;

    ssl_certificate /etc/letsencrypt/live/fch-catechesis.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fch-catechesis.org/privkey.pem;

    location / {
        proxy_pass http://api:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
