ssl_protocols TLSv1.2 TLSv1.3;

ssl_certificate /etc/letsencrypt/live/fch-catechesis.org/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/fch-catechesis.org/privkey.pem;

ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
ssl_session_tickets off;

ssl_stapling on;
ssl_stapling_verify on;

resolver 1.1.1.1 1.0.0.1 valid=300s;
resolver_timeout 5s;

ssl_buffer_size 4k;

